### ISSUE TITLE
Embotic Title covers tabs | Samsung Galaxy S9+

### ISSUE THREAD

**Issue by SuperEvilLuke** [xdlivecat/EmboticApp#6]
![image](https://github.com/xdlivecat/EmboticApp/assets/97245327/110f2fee-16cc-4e7f-bb5a-cd8b3127a99e)
As you can see in the image provided, the name tab thing is covering the icons to navigate to different tabs

**Comment by xdlivecat** [comment]
classic issue of me not properly making the layout, will fix

**Comment by SuperEvilLuke** [comment]
you also cannot access them in portrait

**Comment by xdlivecat** [comment]
seem to have broken it even more

**Comment by xdlivecat** [comment]
@SuperEvilLuke Not an issue with action bar, seems to be an issue with the actual site as even after removing it the tabs are still nowhere

**Comment by TheAutisticChicken** [comment]
yeah something broke there

**Comment by xdlivecat** [comment]
Issue not fixable on my end, closing

**Comment by xdlivecat** [comment]
After more testing I can confirm it is an issue on my end and that the WebView is being cut off at the top. Will fix this in V1.32

**Comment by xdlivecat** [comment]
Issue fixed in v1.31 (I can't keep track of updates is it 1.32 or)

**Comment by SuperEvilLuke** [comment]
ok

**Comment by xdlivecat** [comment]
kind of fixed itself tbf, tabs are now hidden in a menu at the bottom following a ui change
