### ISSUE TITLE
Stuck at White screen. [Embotic App Beta - Huawei Mediapad T5]

### ISSUE THREAD

**Issue by neilsisahuman** [xdlivecat/EmboticApp#9]
So when opening the Beta version of the embotic app it won't show anything just a white screen and the advertisements.

**Comment by xdlivecat** [comment]
are you on the latest version, if I even released a new one

**Comment by neilsisahuman** [comment]
yeah

**Comment by xdlivecat** [comment]
ur gonna have to wait until I push an update out to internal testing as I'm dumb or try this version: https://xdliverblx.live/beta/embotic/app-release.apk

**Comment by onlyjonathan** [comment]
hi

**Comment by xdlivecat** [comment]
> ur gonna have to wait until I push an update out to internal testing as I'm dumb or try this version: https://xdliverblx.live/beta/embotic/app-release.apk

don't use this version anymore but update via google play

**Comment by xdlivecat** [comment]
Issue not updated, marked as resolved.
